name: open_file
description: A plug-in that can call native APP to open files with string result in flutter, support iOS(UTI) / android(intent) / PC(ffi) / web(dart:html)
version: 4.1.4
homepage: https://github.com/javaherisaber/open_file

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2

dev_dependencies:
  flutter_lints: ^1.0.4

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: ">=2.8.1"

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.crazecoder.openfile
        pluginClass: OpenFilePlugin
      ios:
        pluginClass: OpenFilePlugin